# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'SwiftSideMenu' do

pod 'ENSwiftSideMenu', :git => 'https://github.com/re-mondes/ENSwiftSideMenu.git'

end

target 'SwiftSideMenuTests' do

end

